### ISSUE TITLE
horizontal scrolling

### ISSUE THREAD

**Issue by ccebrecos** [casadelamuntanya/screens#3]
With the decided combo (rpi with raspbian + firefox esr) horizontal scrolling does not work properly.

Suggest: put buttons with arrows to allow the horizontal movement.

**Comment by markusand** [comment]
We can try with a custom directive that emulates the scrolling functionality. I've previously used https://github.com/donmbelembe/vue-dragscroll, works fine but it lacks of inertia functionality and doesn't feel very natural :(

**Comment by markusand** [comment]
Scrolling apparently works fine until a specific moment where it stops working properly.

**Comment by markusand** [comment]
Scrolling stops working from a certain point.
